import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import ReactQueryProvider from '../components/ReactQueryProvider/ReactQueryProvider';
import { ToastContainer } from 'react-toastify';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
		<html lang="en">
		<body
			className={`${geistSans.variable} ${geistMono.variable} antialiased`}
		>
			<ReactQueryProvider>
				{/* <Wrapper decodeToken={decode}> */}
					{/* <header className="hidden md:block">
						<Header decodeToken={decode}/>
					</header> */}
					<ToastContainer
						position="top-right"
						autoClose={5000}
						hideProgressBar={false}
						newestOnTop={false}
						closeOnClick={false}
						rtl={false}
						pauseOnFocusLoss
						draggable={false}
						pauseOnHover
						theme="light"
					/>

					<main className="pb-16 md:pb-0">{children}</main>

					{/* <footer className="block md:hidden fixed bottom-0 w-full">
						<BottomNav decodeToken={decode}/>
					</footer> */}
				{/* </Wrapper> */}

			</ReactQueryProvider>
		</body>
		</html>
	);
}
